# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire source code
COPY . .

# Build the project
RUN npm run build

# Stage 2: Run
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy the build artifacts from the builder
COPY --from=builder /app/dist ./dist

# Copy package.json and package-lock.json for production dependencies
COPY --from=builder /app/package*.json ./

# Install production dependencies only
RUN npm install --omit=dev

# Environment variables
ENV NODE_ENV=production

# Command to run the server
ENTRYPOINT ["node", "dist/server.js"]
